# Generated by Django 5.1.4 on 2025-01-12 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_folder_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='content',
            field=models.URLField(),
        ),
    ]
