# Generated by Django 5.1.4 on 2025-01-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_alter_file_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='content',
            field=models.CharField(),
        ),
    ]
