# Generated by Django 5.1.4 on 2025-01-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_alter_file_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='filehistory',
            name='size',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filehistory',
            name='content',
            field=models.CharField(),
        ),
    ]
