# Generated by Django 5.1.4 on 2025-01-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_filehistory_size_alter_filehistory_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='filehistory',
            name='unique_name',
            field=models.CharField(default='', verbose_name=255),
            preserve_default=False,
        ),
    ]
