# Generated by Django 5.1.4 on 2025-01-16 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0009_filehistory_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filehistory',
            old_name='author',
            new_name='history_author',
        ),
        migrations.RenameField(
            model_name='filehistory',
            old_name='content',
            new_name='history_content',
        ),
        migrations.RenameField(
            model_name='filehistory',
            old_name='size',
            new_name='history_size',
        ),
        migrations.RenameField(
            model_name='filehistory',
            old_name='unique_name',
            new_name='history_unique_name',
        ),
        migrations.RenameField(
            model_name='filehistory',
            old_name='version',
            new_name='history_version',
        ),
    ]
