# Generated by Django 5.1.4 on 2025-01-29 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0011_remove_folder_type_alter_folder_parent_folder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('EDITED', 'Edited'), ('DELETED', 'Deleted'), ('RESTORED', 'Restored')], max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='files.file')),
                ('file_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='files.filehistory')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='files.folder')),
            ],
        ),
    ]
