# Generated by Django 5.1.4 on 2025-02-01 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0012_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='files.file'),
        ),
        migrations.AlterField(
            model_name='history',
            name='file_history',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='files.filehistory'),
        ),
        migrations.AlterField(
            model_name='history',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='files.folder'),
        ),
    ]
