# Generated by Django 5.1.4 on 2025-02-01 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0013_alter_history_file_alter_history_file_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='description',
            field=models.CharField(max_length=256),
        ),
    ]
