# Generated by Django 5.1.4 on 2025-02-02 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0014_alter_history_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='action',
            field=models.CharField(choices=[('UPLOADED', 'Uploaded'), ('CREATED', 'Created'), ('EDITED', 'Edited'), ('DELETED', 'Deleted'), ('RESTORED', 'Restored')], max_length=20),
        ),
    ]
